### ISSUE TITLE
Screen - Iniciatives

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#118]
**Description**
Screen with same UI as Measures, list of items and the the respective details.

_Website:_ https://covid19estamoson.gov.pt/iniciativas-nacionais/

Verify the categories IDs to check for DEV environment.

**Comment by Vanethos** [comment]
@OldMetalmind I propose we use the same UI as FAQS since it has the same stuff:
* title
* body
* footer
