### ISSUE TITLE
Bug - White screen

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#119]
**Description** 
A white screen shows up and it and doesn't change.

![photo_2020-03-22 17 13 56](https://user-images.githubusercontent.com/404874/77255636-cd955e80-6c60-11ea-8831-63c19e06d45d.jpeg)

**Cause**
It doesn't always happen, but these have been some of the cases:
- When opening the app
- Minimizing the App and opening again.

**Comment by Vanethos** [comment]
@OldMetalmind did you try with the latest versio of the app?

**Comment by OldMetalmind** [comment]
Yes.

**Comment by OldMetalmind** [comment]
Have been using the app since the fix and haven't happened again.
