### ISSUE TITLE
Bug - Looses track of last screen

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#120]
**Description**
When navigating the app and we minimize it, when open again it will open the HomePage

**How to replicate**
Navigate to a detail of a List, minimize the app and open it again.

**Comment by Vanethos** [comment]
I can't replicate this issue @OldMetalmind 

Is this in Android? iOS?

**Comment by OldMetalmind** [comment]
Android device.

**Comment by Vanethos** [comment]
I'll update this because I've seen it.

While working in the Remote Work page I saw that:

Navigate to:
Home > List > Details

When navigating back from Details to List, the list is empty
