### ISSUE TITLE
Parse of wp/json

### ISSUE THREAD

**Issue by Vanethos** [vostpt/covid19-mobile#16]
**NOTE**
Everything that is stipulated in this issue is still a work-in-progress. This issue serves as a discussion board for how we should parse the json and show it.

The following endpoint will be used to receive data:

https://dev-covid19.vost.pt/wp-json

All available pages for the app will be displayed here:

https://dev-covid19.vost.pt/wp-json/wp/v2/pages

**Comment by OldMetalmind** [comment]
Endpoints suffered too many changes.
We will follow up with them in separated issues and record this research.
