### ISSUE TITLE
Bug - Error on opening FAQs

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#180]
**Description**

From the latest `dev` branch at the moment of the creation of this issue. 
When clicking "Perguntas Frequentes" in the Home page it gives the following error

![photo_2020-03-24 17 16 53](https://user-images.githubusercontent.com/30554430/77456644-6d82f180-6df3-11ea-98e5-9874a2f84c8d.jpeg)

**Expected**

Open FAQ Categories List

**Comment by Vanethos** [comment]
Restest on the latest version please
