### ISSUE TITLE
Bug - Clicking the Slider & Navigating back to the APP

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#181]
**Description**

Clicking the Slider and navigating out of the application, when we come back through "back" it will open the `Splash Page` and run the respective logo animation.

**Expected**

To show the Home page as we left, without passing the `Splash page`.

**Comment by Vanethos** [comment]
I don't see this behaviour, when I click back it goes back to the home page 

Are you testing in a simulator or real device? Android or iOS?
