### ISSUE TITLE
UI Fixes Statistics

### ISSUE THREAD

**Issue by Vanethos** [vostpt/covid19-mobile#194]
![imagem](https://user-images.githubusercontent.com/10728633/77548763-e42cf700-6ea6-11ea-9ef5-20de3f700384.png)

The link for ESRI is:
https://bit.ly/APP2DGS

**Comment by CodeGlitch** [comment]
Will need to add a new line on both sides or they won't be aligned.
Where should the link go to? ( esri-portugal.pt or other link? )
