### ISSUE TITLE
Component - Statistics_Card_Big

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#20]
**Widget**: Statistics_Card_Big

**Image**:
<img width="353" alt="Screenshot 2020-03-18 at 18 28 03" src="https://user-images.githubusercontent.com/404874/76994429-41c0c100-6946-11ea-9711-640855bedf44.png">

**Dimensions**: https://zpl.io/2j0wwvO

**Inputs**
- String: title
- `Statistics_Number_Big`: Reuses widget to mention the recovered number
- `Statistics_Number_Small`: 4 x Widgets of the current status
- `Link`: Reuses widgets

**Notes**:
- Dependent on the implementation of the following widgets: `Statistics_Number_Big`, `Statistics_Number_Small`, and `Link`
- The background is not transparent;

**Comment by CodeGlitch** [comment]
This widget has been created a long with the statistics screen.
