### ISSUE TITLE
Not opening the answer for certain FAQs

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#215]
**Description**
Certain FAQs do not open the answer

**Replicate the problem**
1. Go to FAQs
2. Open "Saude"
3. Try to open any FAQ after "Como é feito o report de dados positivos ou não confirmados, dos casos analiados À DGS".

**Expectation**
To show the answer to the questions

**Comment by Vanethos** [comment]
I can open them
(On a phone, can't post picture)

**Comment by Vanethos** [comment]
What happens is that we are scrolling upwards when clicking on it

**Comment by OldMetalmind** [comment]
Even if I click on the question, and carefully scroll back, I can't see the answer.
It would be best that the screen didn't move.
