### ISSUE TITLE
Add Selectable Text

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#217]
**Request** 
It would be useful to be able to copy content text from FAQs, Initiatives or Measures. 
To copy for example some phone numbers.

**Comment by JorgeMiguelGomes** [comment]
> **Request**
> It would be useful to be able to copy content text from FAQs, Initiatives or Measures.
> To copy for example some phone numbers.

I would make this request more general and make a proposal to think about general shareability and follow through with phone numbers (by opening the keypad on the phone) and e-mails (opening the default mail app)
