### ISSUE TITLE
Component - Play_Button

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#22]
**Widget**: Play_Button

**Image**:
<img width="115" alt="Play_button" src="https://user-images.githubusercontent.com/404874/76883625-5e8cc400-6874-11ea-8a93-9c8423208703.png">

**Dimensions/style**: https://zpl.io/a38lzR1

**Inputs**: N/A

**Notes**:
- Required to determine what would be animation onClick, loading(?), disabled ...
- Required to create a callback of the interaction with the button

**Questions**
- Will the video be played in the app or externally? (ex.: Youtube)

**Comment by miguelpruivo** [comment]
This will be embedded with #26.
