### ISSUE TITLE
Organize lists alphabetically. Add top categories.

### ISSUE THREAD

**Issue by ffrutuoso** [vostpt/covid19-mobile#227]
New page for "Medidas Excepcionais". All lists could be organized alphabetically,  from now on.
![image](https://user-images.githubusercontent.com/13594537/77834879-0b522580-7140-11ea-835a-ed5bc916bc84.png)

The website also has categories that have more importance than the rest. These should be filled green and stay on top.
![image](https://user-images.githubusercontent.com/13594537/77834957-b6fb7580-7140-11ea-9cd5-58f6566ed7fc.png)

**Comment by Lima21** [comment]
Vou resolver :)
