### ISSUE TITLE
Fix numbered lists on content.

### ISSUE THREAD

**Issue by ffrutuoso** [vostpt/covid19-mobile#232]
Numbered lists don't go past the first number. 
Screenshot from `Medidas Excepcionais > Serviços Públicos`, but it prevalent throughout the entire app.

![Screenshot_20200330-131010](https://user-images.githubusercontent.com/13594537/77911040-10ba8780-7288-11ea-8ab3-047eb6676ebd.png)

**Comment by Vanethos** [comment]
@ffrutuoso when reporting a bug like this, please put the title and where the content is from (measures/faqs, etc..) and the corresponding webpage on the Estamos On website

We need to verify if this is just an error from the HTML content or not

**Comment by ffrutuoso** [comment]
> @ffrutuoso when reporting a bug like this, please put the title and where the content is from (measures/faqs, etc..) and the corresponding webpage on the Estamos On website
> 
> We need to verify if this is just an error from the HTML content or not

Updated the first post. It is not an error specific to any section. I've found it in the content of other setions as well.

**Comment by Vanethos** [comment]
I may investigate this, but I think this is due to the fact of how lists are displayed in the parser.

Each time you do something like this:

* This is a list

It will add some padding to the left of the bulletpoint/number:

1. This is a numbered list

Which is the default behaviour in this case

**Comment by ffrutuoso** [comment]
Im not sure if you understood what I meant. My issue is not the padding, but the number being the same. It is only 1's, but the list on the website goes further.

![image](https://user-images.githubusercontent.com/13594537/78906169-eaaa9980-7a76-11ea-8b33-0735b9242728.png)
