### ISSUE TITLE
Add Statistics with history

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#237]
**Description**

Currently, we only show the current status of the epidemic in the Stats screen. The is no way to see the status of the day before or the week

**Suggestion**

Create a screen with the history of the evolution of the pandemic.

**Comment by ffrutuoso** [comment]
Do we have the data for this? Can I look to the available data points to draw some graphs?

**Comment by OldMetalmind** [comment]
@ffrutuoso we still don't have still a way to show the history of cases.

**Comment by Vanethos** [comment]
closed via #256

@OldMetalmind if you disapprove, please reopen it
