### ISSUE TITLE
Statistics Screen with more information

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#241]
**Description**

Currently, the statistics screen shows the current absolute values of the epidemy

**Suggestion**

Add more information, such as:
- Average duration, in days, between patients' admission to the ICU and discharge;
- Breakdown of discharge reasons between cure and/or discharge from hospital (1), transfer to general inpatient care (2), death of patient (3)

--- 
Complements #235

**Comment by JorgeMiguelGomes** [comment]
The idea is great but we don't have the data to fulfill this request.

Add % daily variation of the data we display in the app is more feasible but it will need some database storage and UI implementation

**Comment by Vanethos** [comment]
Closed via #255
