### ISSUE TITLE
Add missing content to Remote Work section

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#249]
**Description**

Remote Work is showing data from different solutions and showing data from the field `description`. 
However, there are other fields that the detail of a `remote work` should look at, such as: 
- `post_title`
- `como_aceder`
- `suporte_tecnico` 

**Objective** 

Serve this issue to add the missing information to the Remote Work detail screen to show all information one after the other.

**Comment by tomahock** [comment]
@OldMetalmind that information is available here: https://covid19estamoson.gov.pt/wp-json/vost/v1/remote_work

Do you need something else from the API?

**Comment by OldMetalmind** [comment]
@tomahock do you know what might come in the field `formacao_em_portugues`, is it also HTML?

**Comment by tomahock** [comment]
> @tomahock do you know what might come in the field `formacao_em_portugues`, is it also HTML?

@OldMetalmind it's an url but as far as I can see it's empty on all posts!
![Screenshot 2020-04-07 at 15 40 05](https://user-images.githubusercontent.com/794581/78682600-1a766780-78e6-11ea-806b-fdb734b8f78e.png)
