### ISSUE TITLE
Component - Header_Back

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#25]
**Widget**: Header_Back

**Image**:
<img width="487" alt="Header_Back" src="https://user-images.githubusercontent.com/404874/76884527-bbd54500-6875-11ea-8257-e1ff07142378.png">

**Dimensions/Styles**: https://zpl.io/awD10Og

**Inputs**
- String : Title

**Notes**:
- To be used when back navigation it is possible;
- The back arrow should be add automatically by flutter

**Comment by CodeGlitch** [comment]
Discontinued.
