### ISSUE TITLE
Split "Medidas de apoio à economia" to a new menu entry

### ISSUE THREAD

**Issue by ffrutuoso** [vostpt/covid19-mobile#251]
Currently, the links to "Medidas de apoio à economia" are filling the entire screen and creating a list too long. The number of links in this content justifies the existence of another endpoint instead of joining them together.

![image](https://user-images.githubusercontent.com/13594537/78907983-5beb4c00-7a79-11ea-94d5-36b27b4c3265.png)

### **SUGESTIONS:**
![image](https://user-images.githubusercontent.com/13594537/78908304-cb613b80-7a79-11ea-9e52-57363b720695.png)

The title string could also be trimmed, repeating information just decreases readability.

![image](https://user-images.githubusercontent.com/13594537/78908635-488cb080-7a7a-11ea-9dae-823e7e0b7ea2.png)

**Comment by ffrutuoso** [comment]
CC @JorgeMiguelGomes

**Comment by JorgeMiguelGomes** [comment]
@ffrutuoso great suggestion. I'll pass it along.
