### ISSUE TITLE
1.0.2 Bar graphs axis labels not showing up

### ISSUE THREAD

**Issue by ffrutuoso** [vostpt/covid19-mobile#277]
![image](https://user-images.githubusercontent.com/13594537/87081483-5db3df80-c221-11ea-81de-e3d753e3fde2.png)
![image](https://user-images.githubusercontent.com/13594537/87081491-61476680-c221-11ea-8291-26c1a17b72a4.png)

If I understand correctly, it is an issue with the axis interval being calculated for the entire data, instead of the data that is directly inside the view.

**Comment by OldMetalmind** [comment]
Deprecated
