### ISSUE TITLE
2.0 Cases per region

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/covid19-mobile#295]
# Description

Create a new graph in **Confirmed Cases** called "Casos por Região" in which we show the cases per region in Portugal.

<img width="711" alt="Screenshot 2021-02-21 at 13 37 15" src="https://user-images.githubusercontent.com/404874/108626814-14c83880-744a-11eb-82cc-1efb995cbaad.png">

**Comment by OldMetalmind** [comment]
We need to find a nice SVG file with the regions of Portugal.

**Comment by Vanethos** [comment]
Found one here:

https://mapsvg.com/maps/portugal-regions

With inkscape I removed Azores and Madeira and resized the document

**EDIT:**
I have added the shapes of Continental Portugal, Açores and Madeira with the correct colors, here:
[portugal-shapes.zip](https://github.com/vostpt/covid19-mobile/files/6017982/portugal-shapes.zip)
