### ISSUE TITLE
Improvement - Create Generic Post Model

### ISSUE THREAD

**Issue by danidroid** [vostpt/covid19-mobile#72]
The API response Post will have the same base fields, the idea is to create this base to reuse in another models:

base model:

> {
        "ID": 198,
        "post_author": "11",
        "post_date": "2020-03-17 19:04:13",
        "post_date_gmt": "2020-03-17 19:04:13",
        "post_content": "",
        "post_title": "Microsoft - Escolas",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "microsoft-escolas",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2020-03-17 23:40:31",
        "post_modified_gmt": "2020-03-17 23:40:31",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "https:\/\/dev-covid19.vost.pt\/?post_type=remote_work&#038;p=198",
        "menu_order": 0,
        "post_type": "remote_work",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw",
       "documentos": false,
       "links": false
    }

**Comment by Vanethos** [comment]
@danidroid 

That seems to be the response from the `Measures` object, the following are the special fields for that object.

*  Endpoint specific parameters:
- `post_title` - `string`
- `post_content` - `string` HTML
- `documentos` - ? undefined
- `links` - ? undefined

So I have removed them, ok?
