### ISSUE TITLE
Firebase Messaging

### ISSUE THREAD

**Issue by Vanethos** [vostpt/covid19-mobile#9]
Add `Firebase Messaging`

https://pub.dev/packages/firebase_messaging

**BLOCKED** - we need access to the Firebase Console

**Comment by OldMetalmind** [comment]
- Shall we consider having a way to add a restricted number of users in a "Group" so we can test notifications before sending to the wider audience?

**Comment by Vanethos** [comment]
@OldMetalmind this can be tested with the DEV firebase project.

Other than that, we can send firebase notiifcations to specific devices given we have their id

**Comment by Vanethos** [comment]
@miguelpruivo is everything set for us to start developing this?

Do we need more certificates/credentials from Apple ?

**Comment by tomahock** [comment]
P8 on firebase isn't there yet.

**Comment by miguelpruivo** [comment]
@tomahock any news on this?

**Comment by tomahock** [comment]
@miguelpruivo I hope will have it soon. WIll update when we have it.

**Comment by miguelpruivo** [comment]
Certificate is set on Firebase console. We can further proceed on this one.
